name: Auto Merge Bot

on:
  # GitHub considers PRs as issues
  issue_comment:
    types: [created]

jobs:
  set-auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Important! This forces the job to run only on comments on Pull Requests that starts with '/merge'
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/merge') }}
    steps:
      - name: Get the GitHub handle of the fellows
        uses: paritytech/get-fellows-action@v1.1.3
        id: fellows
      - name: Generate a token
        id: merge_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MERGE_APP_ID }}
          private-key: ${{ secrets.MERGE_APP_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Set auto merge
        uses: paritytech/auto-merge-bot@v1.0.1
        with:
          GITHUB_TOKEN: ${{ steps.merge_token.outputs.token }}
          MERGE_METHOD: "SQUASH"
          ALLOWLIST: ${{ steps.fellows.outputs.github-handles }}
